meta:
  img_height: 768
  img_width: 768
  seed: 42

model:
  n_filters: 8
  upsample_mode: simple
  net_scaling: [1, 1] # downsampling inside the network
  gaussian_noise: 0.1

preprocessing:
  img_scaling: [3, 3] # downsampling in preprocessing

train:
  learning_rate: 0.01
  batch_size: 64
  epochs: 10
  shuffle: True
  do_augmentation: True
  reduceLROnPlat:
    factor: 0.33
    patience: 2
    min_delta: 0.0001
    min_lr: 0.00000001
    cooldown: 0
  EarlyStopping:
    patience: 5
  checkpoint:
    save_best_only: True
    save_weights_only: True
